--liquibase formatted sql

--This is for the sedmap schema
 
--changeset ajmccart:CreateInstSites
CREATE TABLE SM_INST_SITES
(
  USGS_STATION_ID  VARCHAR2(15 BYTE)
);

ALTER TABLE SM_INST_SITES ADD 
  CONSTRAINT SM_INST_SITE_FACT_PK
 PRIMARY KEY
 (USGS_STATION_ID);
 
 ALTER TABLE SM_INST_SITES ADD (
  CONSTRAINT SM_INST_SITE_FACT_R01 
 FOREIGN KEY (USGS_STATION_ID) 
 REFERENCES SM_SITE_REF (USGS_STATION_ID));
 
 GRANT SELECT ON SM_INST_SITES TO SEDUSER;
 --rollback drop table sm_inst_sites;
 
--changeset ajmccart:CreateInstSample
 CREATE TABLE SM_INST_SAMPLE_FACT
(
  SM_INST_SAMP_SEQ  NUMBER,
  AGENCY_CODE       NUMBER,
  DAILY_FLOW        NUMBER,
  DATETIME          DATE,
  USGS_STAITON_ID   VARCHAR2(25 BYTE),
  DCOMMENT          VARCHAR2(255 BYTE),
  GH                NUMBER,
  ICOMMENT          VARCHAR2(255 BYTE),
  INSTFLOW          NUMBER,
  LOI               NUMBER,
  NUMBERSAMPPTS     NUMBER,
  P125              NUMBER,
  P16               NUMBER,
  P1MILLI           NUMBER,
  P2                NUMBER,
  P250              NUMBER,
  P2MILLI           NUMBER,
  P31               NUMBER,
  P4                NUMBER,
  P500              NUMBER,
  P63               NUMBER,
  P8                NUMBER,
  PH                NUMBER,
  PH_FIELD          NUMBER,
  SAMPLE_CONDITION  NUMBER,
  SAMPLE_PURPOSE    NUMBER,
  SAMPLE_SOURCE     NUMBER,
  SAMP_METHOD       NUMBER,
  SAMP_SPLITTER     NUMBER,
  SAMP_TYPE         NUMBER,
  SC                NUMBER,
  SC_LAB            NUMBER,
  SS                NUMBER,
  SSC               NUMBER,
  TEMP_AIR_C        NUMBER,
  TEMP_C            NUMBER,
  TSS               NUMBER,
  TSSC              NUMBER,
  TURB1350          NUMBER,
  TURB1028          NUMBER,
  TURB3675          NUMBER,
  TURB63676         NUMBER,
  TURB63680         NUMBER,
  TURB70            NUMBER,
  TURB75            NUMBER,
  TURB76            NUMBER,
  TURB88872         NUMBER,
  VELOCITY          NUMBER,
  VERTICALS         NUMBER,
  VISIT_PURPOSE     NUMBER,
  WIDTH             NUMBER
);

ALTER TABLE SM_INST_SAMPLE_FACT ADD 
  CONSTRAINT SM_INST_SAMPLE_FACT_PK
 PRIMARY KEY
 (SM_INST_SAMP_SEQ);
 
 ALTER TABLE SM_INST_SAMPLE_FACT ADD (
  CONSTRAINT SM_INST_SAMPLE_FACT_R01 
 FOREIGN KEY (USGS_STAITON_ID) 
 REFERENCES SM_INST_SITES (USGS_STATION_ID));
 
 GRANT SELECT ON SM_INST_SAMPLE_FACT TO SEDUSER;
 --rollback drop table sm_inst_sample_fact;