--liquibase formatted sql

--This is for the sedmap schema
 
  
--changeset duselman:CreateDaIndex
CREATE INDEX "SEDMAP"."SITE_REF_DA_IDX" ON "SEDMAP"."SITE_REF" ("NWISDA1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_DA_IDX;

--changeset duselman:CreateStateIndex
CREATE INDEX "SEDMAP"."SITE_REF_STATE_IDX" ON "SEDMAP"."SITE_REF" ("STATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_STATE_IDX;
  
--changeset duselman:CreateHucIndex
CREATE INDEX "SEDMAP"."SITE_REF_HUC_IDX" ON "SEDMAP"."SITE_REF" ("HUC_8") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_HUC_IDX;
  
--changeset duselman:CreateEcoIndex
CREATE INDEX "SEDMAP"."SITE_REF_ECO_IDX" ON "SEDMAP"."SITE_REF" ("ECO_L3_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_ECO_IDX;

--changeset duselman:CreateUrbanIndex
CREATE INDEX "SEDMAP"."SITE_REF_URBAN_IDX" ON "SEDMAP"."SITE_REF" ("URBAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_URBAN_IDX;

--changeset duselman:CreateAgricIndex
CREATE INDEX "SEDMAP"."SITE_REF_AGRIC_IDX" ON "SEDMAP"."SITE_REF" ("AGRIC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_AGRIC_IDX;

--changeset duselman:CreateForestIndex
CREATE INDEX "SEDMAP"."SITE_REF_FOREST_IDX" ON "SEDMAP"."SITE_REF" ("FOREST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_FOREST_IDX;
  
--changeset duselman:CreateKFactIndex
CREATE INDEX "SEDMAP"."SITE_REF_KFACT_IDX" ON "SEDMAP"."SITE_REF" ("KFACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_KFACT_IDX;

--changeset duselman:CreateRFactIndex
CREATE INDEX "SEDMAP"."SITE_REF_RFACT_IDX" ON "SEDMAP"."SITE_REF" ("RFACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_RFACT_IDX;

--changeset duselman:CreateClayIndex
CREATE INDEX "SEDMAP"."SITE_REF_CLAY_IDX" ON "SEDMAP"."SITE_REF" ("CLAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_CLAY_IDX;
  
--changeset duselman:CreateSandIndex
CREATE INDEX "SEDMAP"."SITE_REF_Sand_IDX" ON "SEDMAP"."SITE_REF" ("SAND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_SAND_IDX;
  
--changeset duselman:CreateSiltIndex
CREATE INDEX "SEDMAP"."SITE_REF_Silt_IDX" ON "SEDMAP"."SITE_REF" ("SILT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex SITE_REF_SILT_IDX;
  
--changeset duselman:CreateDiscreteYearIndex
CREATE INDEX "SEDMAP"."DISCRETE_SAMPLE_YEAR_IDX" ON "SEDMAP"."DISCRETE_SAMPLE_FACT" (EXTRACT(YEAR FROM "DATETIME")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SEDMAP" ;
--rollback Drop imdex DISCRETE_SAMPLE_YEAR_IDX;



